services:
  gcb-orders-db:
    image: postgres:18
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders -d orders"]
      start_period: 10s
      start_interval: 1s
      interval: "1h"
