---
name: Benchmark
author: Arne Tarara
description: Modular Benchmark script

services:
  benchmark-container:
    image: greencoding/benchmark:latest
    entrypoint: ["sleep", "infinity"]
    cpus: 3
    mem_limit: 8G

flow:

  - name: CPU
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --cpu --cpu-workers 3

  - name: Memory
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --memory

  - name: Disk
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --disk

  - name: Network
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --network

  - name: Idle
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --idle

  - name: Wakeups
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --wakeups

  - name: Syscall
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --syscall