---
name: Benchmark VM
author: Arne Tarara
description: Modular Benchmark script in VM

services:
  benchmark-container:
    image: greencoding/benchmark:latest
    entrypoint: ["sleep", "infinity"]
    docker-run-args:
      - --runtime io.containerd.kata.v2
    # this limit must be 1 core lower than in non-VM scenario as kata-containers will reserve 1 extra core by default
    cpus: 2
    # this limit must be 2G lower than in non-vm scenario as kata-containers will reserve extra 2G by default
    mem_limit: 6G
    networks:
      - bridge

flow:

  - name: Kata Container Limits Validation
    container: benchmark-container
    hidden: True
    commands:
      - type: console
        command: |
          [ "$(nproc)" -eq 3 ] || exit -1
        shell: bash
        note: Checking if exaclty 4 cores are mapped into the VM
      - type: console
        command: |
         [ "$(lsmem -b -n -o SIZE | awk '{s+=$1} END {printf "%.0fG", s/1024/1024/1024}')" = "8G" ]
        shell: bash

  - name: CPU
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --cpu --cpu-workers 3

  - name: Memory
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --memory

  - name: Disk
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --disk

  - name: Network
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --network

  - name: Idle
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --idle

  - name: Wakeups
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --wakeups

  - name: Syscall
    container: benchmark-container
    commands:
        - type: console
          command: bash benchmark.sh --syscall
