---
name: Image Format Rendering Cost - Headful Browser
author: Arne Tarara <arne@green-coding.io>
description: >
  Measures energy cost of loading a single image page for each format
  (avif, gif, jpg, png, webp) served by NGINX, using a headful Firefox browser.

custom_metrics:
  image_page_load:
    unit: Image Page Loads
    sci: True

compose-file: !include-gmt-helper gmt-playwright-headful.yml

services:
  gcb-image-formats-nginx:
    image: nginx:alpine
    folder-destination: /usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/image-formats/index_png.html"]
      start_period: 5s
      start_interval: 1s

  gmt-playwright-nodejs:
    depends_on:
      gcb-image-formats-nginx:
        condition: service_healthy

flow:

  - name: Load AVIF image page
    container: gmt-playwright-nodejs
    commands:
      - type: playwright
        command: |
          for (let i = 1; i <= 50; i++) {
            page_result = await page.goto(`http://gcb-image-formats-nginx/image-formats/index_avif_${i}.html`, { waitUntil: "networkidle" });
          }
      - type: console
        command: echo $(date +%s%N) image_page_load=50
        shell: sh

  - name: Load GIF image page
    container: gmt-playwright-nodejs
    commands:
      - type: playwright
        command: |
          for (let i = 1; i <= 50; i++) {
            page_result = await page.goto(`http://gcb-image-formats-nginx/image-formats/index_gif_${i}.html`, { waitUntil: "networkidle" });
          }
      - type: console
        command: echo $(date +%s%N) image_page_load=50
        shell: sh

  - name: Load JPG image page
    container: gmt-playwright-nodejs
    commands:
      - type: playwright
        command: |
          for (let i = 1; i <= 50; i++) {
            page_result = await page.goto(`http://gcb-image-formats-nginx/image-formats/index_jpg_${i}.html`, { waitUntil: "networkidle" });
          }
      - type: console
        command: echo $(date +%s%N) image_page_load=50
        shell: sh

  - name: Load PNG image page
    container: gmt-playwright-nodejs
    commands:
      - type: playwright
        command: |
          for (let i = 1; i <= 50; i++) {
            page_result = await page.goto(`http://gcb-image-formats-nginx/image-formats/index_png_${i}.html`, { waitUntil: "networkidle" });
          }
      - type: console
        command: echo $(date +%s%N) image_page_load=50
        shell: sh

  - name: Load WebP image page
    container: gmt-playwright-nodejs
    commands:
      - type: playwright
        command: |
          for (let i = 1; i <= 50; i++) {
            page_result = await page.goto(`http://gcb-image-formats-nginx/image-formats/index_webp_${i}.html`, { waitUntil: "networkidle" });
          }
      - type: console
        command: echo $(date +%s%N) image_page_load=50
        shell: sh
