---
name: Bottom Up Benchmark Python HTTP Requests - async (aiohttp)
author: arne@green-coding.io
description: >
  Measure the energy cost of making 10 HTTP requests to https://codetactics.de
  using aiohttp (asynchronous)

custom_metrics:
  http_requests:
    unit: http requests
    sci: True

services:
  python:
    image: python:3.15.0b1-slim-trixie
    setup-commands:
      - command: pip install aiohttp

flow:
  - name: HTTP requests async (aiohttp)
    container: python
    commands:
      - type: console
        shell: bash
        command: |
          python -B /tmp/repo/benchmarks/python/scripts/http_requests_async.py
          echo $(date "+%s%N") 'http_requests=10'
