---
name: Bottom Up Benchmark Python Import Styles - Star
author: arne@green-coding.io
description: >
  Compare the energy cost of Python import styles

custom_metrics:
  import_operations:
    unit: import operations
    sci: True

services:
  python:
    image: python:3.15.0b1-slim-trixie
    setup-commands:
      - command: pip install sympy

flow:
  - name: Import posix
    container: python
    commands:
      - type: console
        shell: bash
        command: |
          for i in {1..1000}; do
            python -B scripts/import_star_posix.py
          done
          echo $(date "+%s%N") 'import_operations=1000'

  - name: Import sympy
    container: python
    commands:
      - type: console
        shell: bash
        command: |
          for i in {1..1000}; do
            python -B scripts/import_star_sympy.py
          done
          echo $(date "+%s%N") 'import_operations=1000'

