---
name: Bottom Up Benchmark Python HTTP Requests - sync (urllib)
author: arne@green-coding.io
description: >
  Measure the energy cost of making 10 HTTP requests to https://codetactics.de
  using Python's built-in urllib (synchronous)

custom_metrics:
  http_requests:
    unit: http requests
    sci: True

services:
  python:
    image: python:3.15.0b1-slim-trixie

flow:
  - name: HTTP requests sync (urllib)
    container: python
    commands:
      - type: console
        shell: bash
        command: |
          python -B /tmp/repo/benchmarks/python/scripts/http_requests_sync.py
          echo $(date "+%s%N") 'http_requests=10'
